# Exercise 1.2.4
Prove that if $A^{-1}$ exists then there can be no nonzero $y$ for which $Ay=0$

$$A^{-1}Ay=A^{-1}0$$

$$AA^{-1}=A^{-1}A=I$$

$$Iy=A^{-1}0$$

$$Iy=0$$

if $A^{-1}$ exists and $Ay=0$, then $y$ must $=0$

# Exercise 1.2.5
Prove that if $A^{-1}$ exists then $det(A)\not=0$

\begin{equation}
    A=
    \left[
    \begin{array}{cc}
        A_{11} & A_{12} \\
        A_{21} & A_{22} \\
    \end{array}
    \right]
\end{equation}

\begin{equation}
    I=
    \left[
    \begin{array}{cc}
        1 & 0 \\
        0 & 1 \\
    \end{array}
    \right]
\end{equation}

$$AA^{-1}=A^{-1}A=I$$

$$det(AA^{-1})=det(I)$$

$$det(I)=(1*1)-(0*0)=1$$

$$det(A)det(A^{-1})=1$$

$$det(A)\not=0$$

 $$det(A^{-1})=\frac{1}{det(A)}=\frac{1}{A_{11}A_{22}-A_{21}A_{12}}$$

# Exercise 1.2.7

In [2]:
from matrixcomp.ch1_2 import solve_for_x
import tensorflow as tf

tf.Tensor(
[[3.0638294]
 [2.4255316]
 [3.7021272]
 [1.148936 ]], shape=(4, 1), dtype=float32)


# Exercise 1.2.9

#### loop 1
$$5(x_{1}-x_{2})+1x_{1}+1x_{1}+2x_{1}=0$$

$$9x_{1}-5x_{2} = 0 $$

#### loop 2 $$5(x_{2}-x_{1})+1x_{2}-6+2x_{2}=0$$

$$-5x_{1}+8x_{2} = 6 $$

\begin{equation}
    \left[
    \begin{array}{cc}
        9 & -5 \\
        -5 & 8 \\
    \end{array}
    \right]
    \left[
    \begin{array}{c}
        x_{1} \\
        x_{2} \\
    \end{array}
    \right]
    =
    \left[
    \begin{array}{c}
        0 \\
        6 \\
    \end{array}
    \right]
\end{equation}

##### check that the coefficient matrix is nonsingular

\begin{equation}
    det
    \left[
        \begin{array}{cc}
        9 & -5 \\
        -5 & 8 \\
    \end{array}
    \right]
    =
    (9*8)-(-5*-5)=47
\end{equation}

In [3]:
loops_coefficient: tf.Tensor = tf.constant([[9.0, -5.0], [-5.0, 8.0]])
loops_b_matrix: tf.Tensor = tf.constant([[0.0], [6.0]])

In [4]:
loops_nonsingular: tf.Tensor = tf.linalg.det(loops_coefficient)

In [5]:
print(loops_nonsingular)

tf.Tensor(47.000008, shape=(), dtype=float32)


In [6]:
solution: tf.Tensor = solve_for_x(loops_coefficient, loops_b_matrix)

In [7]:
print(solution)

tf.Tensor(
[[0.63829786]
 [1.1489362 ]], shape=(2, 1), dtype=float32)


# Exercise 1.2.11

#### cart 1
$$-4x_{1}+4(x_{2}-x_{1})+1=0$$
$$-4x_{1}+4x_{2}-4x_{1}+1=0$$
$$-8x_{1}+4x_{2}=-1$$
$$8x_{1}-4x_{2}+0x_{3}=1$$

#### cart 2
$$-4(x_{2}-x_{1})+4(x_{3}-x_{2})+2=0$$
$$-4x_{2}+4x_{1}+4x_{3}-4x_{2}+2=0$$
$$-8x_{2}+4x_{1}+4x_{3}=-2$$
$$-4x_{1}+8x_{2}-4x_{3}=2$$


#### cart 3
$$-4x_{3}-4(x_{3}-x_{2})+3=0$$
$$-4x_{3}-4x_{3}+4x_{2}+3=0$$
$$-8x_{3}+4x_{2}=-3$$
$$0x_{1}-4x_{2}+8x_{3}=3$$

\begin{equation}
    \left[
    \begin{array}{ccc}
        8 & -4 & 0\\
        -4 & 8 & -4\\
        0 & -4 & 8\\
    \end{array}
    \right]
    \left[
    \begin{array}{c}
        x_{1} \\
        x_{2} \\
        x_{3} \\
    \end{array}
    \right]
    =
    \left[
    \begin{array}{c}
        1 \\
        2 \\
        3 \\
    \end{array}
    \right]
\end{equation}

##### check that the coefficient matrix is nonsingular

\begin{equation}
    det
    \left[
    \begin{array}{ccc}
        8 & -4 & 0\\
        -4 & 8 & -4\\
        0 & -4 & 8\\
    \end{array}
    \right]
    =
    8det
    \left[
        \begin{array}{cc}
        8 & -4 \\
        -4 & 8 \\
    \end{array}
    \right]
    -
    (-4)det
    \left[
        \begin{array}{cc}
        -4 & -4 \\
        0 & 8 \\
    \end{array}
    \right]
    +
    0det
    \left[
        \begin{array}{cc}
        -4 & 8 \\
        0 & -4 \\
    \end{array}
    \right]
\end{equation}

$$det = 8((8*8)-(-4*-4))-(-4)((-4*8)-(4*0))+0 = 384 - 128 = 256 $$

In [10]:
spring_coefficient: tf.Tensor = tf.constant([[8.0, -4.0, 0.0], [-4.0, 8.0, -4.0], [0.0, -4.0, 8.0]])
spring_b_matrix: tf.Tensor = tf.constant([[1.0], [2.0], [3.0]])

In [11]:
spring_nonsingular: tf.Tensor = tf.linalg.det(spring_coefficient)

In [12]:
print(spring_nonsingular)

tf.Tensor(256.0, shape=(), dtype=float32)


In [7]:
spring_solution = tf.Tensor = solve_for_x(spring_coefficient, spring_b_matrix)

In [8]:
print(spring_solution)

tf.Tensor(
[[0.62500006]
 [1.0000001 ]
 [0.8750001 ]], shape=(3, 1), dtype=float32)


# Exercise 1.2.16

(a) $m=8$ and $h=1/8$

\begin{equation}
    \left[
    \begin{array}{ccccccc}
        128+d & -64+4c & 0 & 0 & 0 & 0 & 0\\
        -64-4c & 128+d & -64+4c & 0 & 0 & 0 & 0\\
        0 & -64+4c & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & -64+4c & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & -64-4c & 128+d & -64+3c\\
        0 & 0 & 0 & 0 & 0 & -64-4c & 128+d\\
    \end{array}
    \right]
    \left[
    \begin{array}{c}
        u_{1} \\
        u_{2} \\
        u_{3} \\
        u_{4} \\
        u_{5} \\
        u_{6} \\
        u_{7} \\
    \end{array}
    \right]
    =
    \left[
    \begin{array}{c}
        f_{1} \\
        f_{2} \\
        f_{3} \\
        f_{4} \\
        f_{5} \\
        f_{6} \\
        f_{7} \\
    \end{array}
    \right]
\end{equation}

(b) $m=20$ and $h=1/20$

\begin{equation}
    \left[
    \begin{array}{ccccccccccccccccccc}
    \end{array}
    \right]
    \left[
    \begin{array}{c}
        u_{1} \\
        u_{2} \\
        u_{3} \\
        u_{4} \\
        u_{5} \\
        u_{6} \\
        u_{7} \\
        u_{8} \\
        u_{9} \\
        u_{10} \\
        u_{11} \\
        u_{12} \\
        u_{13} \\
        u_{14} \\
        u_{15} \\
        u_{16} \\
        u_{17} \\
        u_{18} \\
        u_{19} \\
    \end{array}
    \right]
    =
    \left[
    \begin{array}{c}
        f_{1} \\
        f_{2} \\
        f_{3} \\
        f_{4} \\
        f_{5} \\
        f_{6} \\
        f_{7} \\
        f_{8} \\
        f_{9} \\
        f_{10} \\
        f_{11} \\
        f_{12} \\
        f_{13} \\
        f_{14} \\
        f_{15} \\
        f_{16} \\
        f_{17} \\
        f_{18} \\
        f_{19} \\
    \end{array}
    \right]
\end{equation}

# Exercise 1.2.17

$$12x_{1}-2x_{2}+0x_{3}-10x_{4}+0x_{5}+0x_{6}+0x_{7}=0$$

$$-2x_{1}+9x_{2}-5x_{3}+0x_{4}-2x_{5}+0x_{6}+0x_{7}=0$$

$$0x_{1}-5x_{2}+15x_{3}+0x_{4}+0x_{5}-10x_{6}+0x_{7}=0$$

$$-10x_{1}+0x_{2}+0x_{3}+25x_{4}-10x_{5}+0x_{6}-5x_{7}=0$$

$$0x_{1}-2x_{2}+0x_{3}-10x_{4}+24x_{5}-2x_{6}+0x_{7}=90$$

$$0x_{1}+0x_{2}-10x_{3}+0x_{4}-2x_{5}+17x_{6}+0x_{7}=0$$

$$0x_{1}+0x_{2}+0x_{3}-5x_{4}+0x_{5}+0x_{6}+10x_{7}=45$$

\begin{equation}
    \left[
    \begin{array}{ccccccc}
        12 & -2 & 0 & -10 & 0 & 0 & 0\\
        -2 & 9 & -5 & 0 & -2 & 0 & 0\\
        0 & -5 & 15 & 0 & 0 & -10 & 0\\
        -10 & 0 & 0 & 25 & -10 & 0 & -5\\
        0 & -2 & 0 & -10 & 24 & -2 & 0\\
        0 & 0 & -10 & 0 & -2 & 17 & 0\\
        0 & 0 & 0 & -5 & 0 & 0 & 10\\
    \end{array}
    \right]
    \left[
    \begin{array}{c}
        x_{1} \\
        x_{2} \\
        x_{3} \\
        x_{4} \\
        x_{5} \\
        x_{6} \\
        x_{7} \\
    \end{array}
    \right]
    =
    \left[
    \begin{array}{c}
        0 \\
        0 \\
        0 \\
        0 \\
        90 \\
        0 \\
        45 \\
    \end{array}
    \right]
\end{equation}

In [9]:
voltages_coefficient: tf.Tensor = tf.constant([[12.0, -2.0, 0.0, -10.0, 0.0, 0.0, 0.0], 
                                               [-2.0, 9.0, -5.0, 0.0, -2.0, 0.0, 0.0],
                                               [0.0, -5.0, 15.0, 0.0, 0.0, -10.0, 0.0],
                                               [-10.0, 0.0, 0.0, 25.0, -10.0, 0.0, -5.0],
                                               [0.0, -2.0, 0.0, -10.0, 24.0, -2.0, 0.0],
                                               [0.0, 0.0, -10.0, 0.0, -2.0, 17.0, 0.0],
                                               [0.0, 0.0, 0.0, -5.0, 0.0, 0.0, 10.0]
                                              ])
voltages_b_matrix: tf.Tensor = tf.constant([[0.0], [0.0], [0.0], [0.0], [90.0], [0.0], [45.0]])

In [10]:
voltage_solution = tf.Tensor = solve_for_x(voltages_coefficient, voltages_b_matrix)

In [11]:
print(voltage_solution)

tf.Tensor(
[[7.324737 ]
 [5.5898747]
 [4.0572357]
 [7.6717095]
 [7.686611 ]
 [3.2909162]
 [8.335855 ]], shape=(7, 1), dtype=float32)


Calculate the residual $r=b-A\hat{x}$

In [12]:
from matrixcomp.ch1_2 import residual

In [13]:
residual(voltages_coefficient, voltages_b_matrix, voltage_solution)

<tf.Tensor: id=13, shape=(7, 1), dtype=float32, numpy=
array([[0.0000000e+00],
       [3.8146973e-06],
       [0.0000000e+00],
       [7.6293945e-06],
       [7.6293945e-06],
       [3.8146973e-06],
       [3.8146973e-06]], dtype=float32)>

# Exercise 1.2.18

##### part (a)

$$1.2x_{1}-.1x_{2}-.5x_{3}+0x_{4}=0$$

$$-.1x_{1}+.6x_{2}+0x_{3}-.1x_{4}=0$$

$$-.5x_{1}+0x_{2}+1.3x_{3}-.5x_{4}=0$$

$$0x_{1}-.1x_{2}-.5x_{3}+8x_{4}=9$$

\begin{equation}
    \left[
    \begin{array}{cccc}
        1.2 & -0.1 & -0.5 & 0\\
        -0.1 & 0.6 & 0 & -0.1\\
        -0.5 & 0 & 1.3 & -0.5\\
        0 & -0.1 & -0.5 & 0.8\\
    \end{array}
    \right]
    \left[
    \begin{array}{c}
        x_{1} \\
        x_{2} \\
        x_{3} \\
        x_{4} \\
    \end{array}
    \right]
    =
    \left[
    \begin{array}{c}
        0 \\
        0 \\
        0 \\
        9 \\
    \end{array}
    \right]
\end{equation}

In [14]:
loops_coefficient: tf.Tensor = tf.constant([[1.2, -0.1, -0.5, 0.0], 
                                               [-0.1, 0.6, 0.0, -0.1],
                                               [-0.5, 0.0, 1.3, -0.5],
                                               [0.0, -0.1, -0.5, 0.8],
                                              ])
loops_b_matrix: tf.Tensor = tf.constant([[0.0], [0.0], [0.0], [9.0]])

In [15]:
loops_solution = tf.Tensor = solve_for_x(loops_coefficient, loops_b_matrix)

##### part (b)

In [16]:
print(loops_solution)

tf.Tensor(
[[ 3.4697258]
 [ 3.3207192]
 [ 7.6631985]
 [16.45459  ]], shape=(4, 1), dtype=float32)


In [17]:
residual(loops_coefficient, loops_b_matrix, loops_solution)

<tf.Tensor: id=18, shape=(4, 1), dtype=float32, numpy=
array([[ 2.3841858e-07],
       [ 0.0000000e+00],
       [ 9.5367432e-07],
       [-9.5367432e-07]], dtype=float32)>

##### part (c)

$$(V_{n_{1}}-V_{n_{2}})=0.2I_{x_{3}}$$

$$(V_{n_{1}}-V_{n_{2}})=0.2(3.4697258-7.6631985)$$

$$(V_{n_{1}}-V_{n_{2}})= $$

$$(V_{n_{1}}-V_{n_{3}})=0.5I_{x_{1}-x_{3}}$$

##### part (d)

$$(V_{x_{1}}-V_{x_{2}})=0.5I_{R_{1}}$$

$$(7.324737-5.5898747)=0.5I_{R_{1}}$$

$$(1.7348623) * 2 = 3.4697246 $$

# Exercise 1.2.19

$$3x_{1}-1x_{2}+0x_{3}-1x_{4}+0x_{5}+0x_{6}+0x_{7}+0x_{8}+0x_{9}=0$$
$$-1x_{1}+4x_{2}-1x_{3}+0x_{4}-1x_{5}+0x_{6}+0x_{7}+0x_{8}+0x_{9}=0$$
$$0x_{1}-1x_{2}+3x_{3}+0x_{4}+0x_{5}-1x_{6}+0x_{7}+0x_{8}+0x_{9}=0$$
$$-1x_{1}+0x_{2}+0x_{3}+4x_{4}-1x_{5}+0x_{6}-1x_{7}+0x_{8}+0x_{9}=0$$
$$0x_{1}-1x_{2}+0x_{3}-1x_{4}+4x_{5}-1x_{6}+0x_{7}-1x_{8}+0x_{9}=0$$
$$0x_{1}+0x_{2}-1x_{3}+0x_{4}-1x_{5}+4x_{6}+0x_{7}+0x_{8}-1x_{9}=0$$
$$0x_{1}+0x_{2}+0x_{3}-1x_{4}+0x_{5}+0x_{6}+3x_{7}-1x_{8}+0x_{9}=0$$
$$0x_{1}+0x_{2}+0x_{3}+0x_{4}-1x_{5}+0x_{6}-1x_{7}+4x_{8}-1x_{9}=0$$
$$0x_{1}+0x_{2}+0x_{3}+0x_{4}+0x_{5}-1x_{6}+0x_{7}-1x_{8}+3x_{9}=9$$

\begin{equation}
    \left[
    \begin{array}{ccccccc}
        3 & -1 & 0 & -1 & 0 & 0 & 0 & 0 & 0\\
        -1 & 4 & -1 & 0 & -1 & 0 & 0 & 0 & 0\\
        0 & -1 & 3 & 0 & 0 & -1 & 0 & 0 & 0\\
        -1 & 0 & 0 & 4 & -1 & 0 & -1 & 0 & 0\\
        0 & -1 & 0 & -1 & 4 & -1 & 0 & -1 & 0\\
        0 & 0 & -1 & 0 & -1 & 4 & 0 & 0 & -1\\
        0 & 0 & 0 & -1 & 0 & 0 & 3 & -1 & 0\\
        0 & 0 & 0 & 0 & -1 & 0 & -1 & 4 & -1\\
        0 & 0 & 0 & 0 & 0 & -1 & 0 & -1 & 3\\
    \end{array}
    \right]
    \left[
    \begin{array}{c}
        x_{1} \\
        x_{2} \\
        x_{3} \\
        x_{4} \\
        x_{5} \\
        x_{6} \\
        x_{7} \\
        x_{8} \\
        x_{9} \\
    \end{array}
    \right]
    =
    \left[
    \begin{array}{c}
        0 \\
        0 \\
        0 \\
        0 \\
        0 \\
        0 \\
        0 \\
        0 \\
        9 \\
    \end{array}
    \right]
\end{equation}

In [18]:
oneloops_coefficient: tf.Tensor = tf.constant([[3.0, -1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
                                               [-1.0, 4.0, -1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0],
                                               [0.0, -1.0, 3.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0],
                                               [-1.0, 0.0, 0.0, 4.0, -1.0, 0.0, -1.0, 0.0, 0.0],
                                               [0.0, -1.0, 0.0, -1.0, 4.0, -1.0, 0.0, -1.0, 0.0],
                                               [0.0, 0.0, -1.0, 0.0, -1.0, 4.0, 0.0, 0.0, -1.0],
                                               [0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 3.0, -1.0, 0.0],
                                               [0.0, 0.0, 0.0, 0.0, -1.0, 0.0, -1.0, 4.0, -1.0],
                                               [0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, -1.0, 3.0]
                                              ])
oneloops_b_matrix: tf.Tensor = tf.constant([[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [9.0]])

In [19]:
one_loops_solution = tf.Tensor = solve_for_x(oneloops_coefficient, oneloops_b_matrix)

In [20]:
print(one_loops_solution)

tf.Tensor(
[[0.30000004]
 [0.45000008]
 [0.6       ]
 [0.45000005]
 [0.90000015]
 [1.35      ]
 [0.60000014]
 [1.3500001 ]
 [3.9       ]], shape=(9, 1), dtype=float32)


# Exercise 1.2.20

##### part(a)

$$(k_{1}+k_{2})x_{1}-k_{2}x_{2}...+0x_{n-2}+0x_{n-1}+0x_{n}=f_{1}$$
$$-k_{2}x_{1}+(k_{2}+k_{3})x_{2}-k_{3}x_{3}...+0x_{n-2}+0x_{n-1}+0x_{n}=f_{2}$$
$$0x_{1}-(k_{3})x_{2}++(k_{3}+k_{4})x_{3}-k_{4})x_{4}...+0x_{n-2}+0x_{n-1}+0x_{n}=f_{3}$$
$$0x_{1}-0x_{2}...-k_{n-1}x_{n-2}+(k_{n-1}+k_{n})x_{n-1}-k_{n}x_{n}=f_{n-1}$$
$$(k_{1}+k_{2})x_{1}-(k_{2})x_{2}...+0x_{n-2}+k_{n}x_{n-1}+(k_{n-1}+k_{n})x_{n}=f_{n}$$

\begin{equation}
    \left[
    \begin{array}{ccccccc}
        k_{1}+k_{2} & -k_{2} & 0 & 0 & 0 & 0 & 0 & 0\\
        -k_{2} & k_{2}+k_{3} & -k_{3} & 0 & 0 & 0 & 0 & 0\\
        0 & -k_{3} & k_{3}+k_{4} & -k_{4} & 0 & 0 & 0 & 0\\
        . & . & . & . & . & . & . & .\\
        . & . & . & . & . & . & . & .\\
        . & . & . & . & . & . & . & .\\
        0 & 0 & 0 & 0 & 0 & -k_{n-1} & k_{n-1}+k_{n} & -k_{n}\\
        0 & 0 & 0 & 0 & 0 & 0 & -k_{n} & k_{n-1}+k_{n}\\
    \end{array}
    \right]
    \left[
    \begin{array}{c}
        x_{1} \\
        x_{2} \\
        x_{3} \\
        . \\
        . \\
        . \\
        x_{n-1} \\
        x_{n} \\
    \end{array}
    \right]
    =
    \left[
    \begin{array}{c}
        f_{1} \\
        f_{2} \\
        f_{3} \\
        . \\
        . \\
        . \\
        f_{n-1} \\
        f_{n} \\
    \end{array}
    \right]
\end{equation}

##### part(b)

\begin{equation}
    \left[
    \begin{array}{cccccccccccccccccccc}
        2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1 & 0\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2 & -1\\
        0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 2\\
    \end{array}
    \right]
    \left[
    \begin{array}{c}
        x_{1} \\
        x_{2} \\
        x_{3} \\
        x_{4} \\
        x_{5} \\
        x_{6} \\
        x_{7} \\
        x_{8} \\
        x_{9} \\
        x_{10} \\
        x_{11} \\
        x_{12} \\
        x_{13} \\
        x_{14} \\
        x_{15} \\
        x_{16} \\
        x_{17} \\
        x_{18} \\
        x_{19} \\
        x_{20} \\
    \end{array}
    \right]
        =
    \left[
    \begin{array}{c}
        0 \\
        0 \\
        0 \\
        0 \\
        1 \\
        0 \\
        0 \\
        0 \\
        0 \\
        0 \\
        0 \\
        0 \\
        0 \\
        0 \\
        0 \\
        -1 \\
        0 \\
        0 \\
        0 \\
        0 \\
    \end{array}
    \right]
\end{equation}

In [21]:
twentysprings_coefficient: tf.Tensor = tf.constant([
    [2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [-1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
    [0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
    [0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
    [0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0], 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0], 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0], 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0], 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0]])
    
twentysprings_b_matrix: tf.Tensor = tf.constant([
    [0.0], [0.0], [0.0], [0.0], [1.0], [0.0], [0.0], [0.0], [0.0], [0.0], 
    [0.0], [0.0], [0.0], [0.0], [0.0], [-1.0], [0.0], [0.0], [0.0], [0.0]])

In [22]:
twentysprings_solution = tf.Tensor = solve_for_x(twentysprings_coefficient, twentysprings_b_matrix)

In [23]:
print(twentysprings_solution)

tf.Tensor(
[[ 0.5238095 ]
 [ 1.047619  ]
 [ 1.5714284 ]
 [ 2.0952377 ]
 [ 2.6190472 ]
 [ 2.1428566 ]
 [ 1.6666663 ]
 [ 1.190476  ]
 [ 0.7142855 ]
 [ 0.23809503]
 [-0.23809545]
 [-0.7142859 ]
 [-1.1904764 ]
 [-1.6666669 ]
 [-2.1428573 ]
 [-2.6190476 ]
 [-2.0952382 ]
 [-1.5714287 ]
 [-1.0476191 ]
 [-0.5238096 ]], shape=(20, 1), dtype=float32)
